// Mocks generated by Mockito 5.4.4 from annotations
// in befriend/test/models/data/picture_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i19;
import 'dart:io' as _i21;
import 'dart:math' as _i6;

import 'package:befriend/models/data/picture_query.dart' as _i20;
import 'package:befriend/models/data/user_manager.dart' as _i22;
import 'package:befriend/models/objects/bubble.dart' as _i16;
import 'package:befriend/models/objects/friendship.dart' as _i18;
import 'package:befriend/utilities/error_handling.dart' as _i28;
import 'package:cloud_firestore/cloud_firestore.dart' as _i5;
import 'package:device_info_plus/device_info_plus.dart' as _i23;
import 'package:device_info_plus/src/model/android_device_info.dart' as _i7;
import 'package:device_info_plus/src/model/ios_device_info.dart' as _i8;
import 'package:device_info_plus/src/model/linux_device_info.dart' as _i9;
import 'package:device_info_plus/src/model/macos_device_info.dart' as _i11;
import 'package:device_info_plus/src/model/web_browser_info.dart' as _i10;
import 'package:device_info_plus/src/model/windows_device_info.dart' as _i12;
import 'package:device_info_plus_platform_interface/device_info_plus_platform_interface.dart'
    as _i13;
import 'package:flutter/foundation.dart' as _i3;
import 'package:flutter/material.dart' as _i2;
import 'package:flutter/rendering.dart' as _i4;
import 'package:flutter/src/widgets/notification_listener.dart' as _i15;
import 'package:image_cropper/src/cropper.dart' as _i25;
import 'package:image_cropper_platform_interface/image_cropper_platform_interface.dart'
    as _i26;
import 'package:image_picker/image_picker.dart' as _i24;
import 'package:image_picker_platform_interface/image_picker_platform_interface.dart'
    as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i17;
import 'package:permission_handler_platform_interface/permission_handler_platform_interface.dart'
    as _i27;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWidget_0 extends _i1.SmartFake implements _i2.Widget {
  _FakeWidget_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeInheritedWidget_1 extends _i1.SmartFake
    implements _i2.InheritedWidget {
  _FakeInheritedWidget_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeDiagnosticsNode_2 extends _i1.SmartFake
    implements _i3.DiagnosticsNode {
  _FakeDiagnosticsNode_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({
    _i3.TextTreeConfiguration? parentConfiguration,
    _i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info,
  }) =>
      super.toString();
}

class _FakeImageProvider_3<T extends Object> extends _i1.SmartFake
    implements _i4.ImageProvider<T> {
  _FakeImageProvider_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDocumentSnapshot_4<T extends Object?> extends _i1.SmartFake
    implements _i5.DocumentSnapshot<T> {
  _FakeDocumentSnapshot_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePoint_5<T extends num> extends _i1.SmartFake
    implements _i6.Point<T> {
  _FakePoint_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAndroidDeviceInfo_6 extends _i1.SmartFake
    implements _i7.AndroidDeviceInfo {
  _FakeAndroidDeviceInfo_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIosDeviceInfo_7 extends _i1.SmartFake implements _i8.IosDeviceInfo {
  _FakeIosDeviceInfo_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLinuxDeviceInfo_8 extends _i1.SmartFake
    implements _i9.LinuxDeviceInfo {
  _FakeLinuxDeviceInfo_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWebBrowserInfo_9 extends _i1.SmartFake
    implements _i10.WebBrowserInfo {
  _FakeWebBrowserInfo_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMacOsDeviceInfo_10 extends _i1.SmartFake
    implements _i11.MacOsDeviceInfo {
  _FakeMacOsDeviceInfo_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWindowsDeviceInfo_11 extends _i1.SmartFake
    implements _i12.WindowsDeviceInfo {
  _FakeWindowsDeviceInfo_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBaseDeviceInfo_12 extends _i1.SmartFake
    implements _i13.BaseDeviceInfo {
  _FakeBaseDeviceInfo_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLostDataResponse_13 extends _i1.SmartFake
    implements _i14.LostDataResponse {
  _FakeLostDataResponse_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BuildContext].
///
/// See the documentation for Mockito's code generation for more information.
class MockBuildContext extends _i1.Mock implements _i2.BuildContext {
  @override
  _i2.Widget get widget => (super.noSuchMethod(
        Invocation.getter(#widget),
        returnValue: _FakeWidget_0(
          this,
          Invocation.getter(#widget),
        ),
        returnValueForMissingStub: _FakeWidget_0(
          this,
          Invocation.getter(#widget),
        ),
      ) as _i2.Widget);

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get debugDoingBuild => (super.noSuchMethod(
        Invocation.getter(#debugDoingBuild),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i2.InheritedWidget dependOnInheritedElement(
    _i2.InheritedElement? ancestor, {
    Object? aspect,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #dependOnInheritedElement,
          [ancestor],
          {#aspect: aspect},
        ),
        returnValue: _FakeInheritedWidget_1(
          this,
          Invocation.method(
            #dependOnInheritedElement,
            [ancestor],
            {#aspect: aspect},
          ),
        ),
        returnValueForMissingStub: _FakeInheritedWidget_1(
          this,
          Invocation.method(
            #dependOnInheritedElement,
            [ancestor],
            {#aspect: aspect},
          ),
        ),
      ) as _i2.InheritedWidget);

  @override
  void visitAncestorElements(_i2.ConditionalElementVisitor? visitor) =>
      super.noSuchMethod(
        Invocation.method(
          #visitAncestorElements,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void visitChildElements(_i2.ElementVisitor? visitor) => super.noSuchMethod(
        Invocation.method(
          #visitChildElements,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispatchNotification(_i15.Notification? notification) =>
      super.noSuchMethod(
        Invocation.method(
          #dispatchNotification,
          [notification],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.DiagnosticsNode describeElement(
    String? name, {
    _i3.DiagnosticsTreeStyle? style = _i3.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeElement,
          [name],
          {#style: style},
        ),
        returnValue: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #describeElement,
            [name],
            {#style: style},
          ),
        ),
        returnValueForMissingStub: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #describeElement,
            [name],
            {#style: style},
          ),
        ),
      ) as _i3.DiagnosticsNode);

  @override
  _i3.DiagnosticsNode describeWidget(
    String? name, {
    _i3.DiagnosticsTreeStyle? style = _i3.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeWidget,
          [name],
          {#style: style},
        ),
        returnValue: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #describeWidget,
            [name],
            {#style: style},
          ),
        ),
        returnValueForMissingStub: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #describeWidget,
            [name],
            {#style: style},
          ),
        ),
      ) as _i3.DiagnosticsNode);

  @override
  List<_i3.DiagnosticsNode> describeMissingAncestor(
          {required Type? expectedAncestorType}) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeMissingAncestor,
          [],
          {#expectedAncestorType: expectedAncestorType},
        ),
        returnValue: <_i3.DiagnosticsNode>[],
        returnValueForMissingStub: <_i3.DiagnosticsNode>[],
      ) as List<_i3.DiagnosticsNode>);

  @override
  _i3.DiagnosticsNode describeOwnershipChain(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeOwnershipChain,
          [name],
        ),
        returnValue: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #describeOwnershipChain,
            [name],
          ),
        ),
        returnValueForMissingStub: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #describeOwnershipChain,
            [name],
          ),
        ),
      ) as _i3.DiagnosticsNode);
}

/// A class which mocks [Bubble].
///
/// See the documentation for Mockito's code generation for more information.
class MockBubble extends _i1.Mock implements _i16.Bubble {
  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i17.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
        returnValueForMissingStub: _i17.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  String get username => (super.noSuchMethod(
        Invocation.getter(#username),
        returnValue: _i17.dummyValue<String>(
          this,
          Invocation.getter(#username),
        ),
        returnValueForMissingStub: _i17.dummyValue<String>(
          this,
          Invocation.getter(#username),
        ),
      ) as String);

  @override
  String get avatarUrl => (super.noSuchMethod(
        Invocation.getter(#avatarUrl),
        returnValue: _i17.dummyValue<String>(
          this,
          Invocation.getter(#avatarUrl),
        ),
        returnValueForMissingStub: _i17.dummyValue<String>(
          this,
          Invocation.getter(#avatarUrl),
        ),
      ) as String);

  @override
  int get power => (super.noSuchMethod(
        Invocation.getter(#power),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i4.ImageProvider<Object> get avatar => (super.noSuchMethod(
        Invocation.getter(#avatar),
        returnValue: _FakeImageProvider_3<Object>(
          this,
          Invocation.getter(#avatar),
        ),
        returnValueForMissingStub: _FakeImageProvider_3<Object>(
          this,
          Invocation.getter(#avatar),
        ),
      ) as _i4.ImageProvider<Object>);

  @override
  set avatar(_i4.ImageProvider<Object>? _avatar) => super.noSuchMethod(
        Invocation.setter(
          #avatar,
          _avatar,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get birthYear => (super.noSuchMethod(
        Invocation.getter(#birthYear),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  Map<String, dynamic> get blockedUsers => (super.noSuchMethod(
        Invocation.getter(#blockedUsers),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  set blockedUsers(Map<String, dynamic>? _blockedUsers) => super.noSuchMethod(
        Invocation.setter(
          #blockedUsers,
          _blockedUsers,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, DateTime> get lastSeenUsersMap => (super.noSuchMethod(
        Invocation.getter(#lastSeenUsersMap),
        returnValue: <String, DateTime>{},
        returnValueForMissingStub: <String, DateTime>{},
      ) as Map<String, DateTime>);

  @override
  set lastSeenUsersMap(Map<String, DateTime>? _lastSeenUsersMap) =>
      super.noSuchMethod(
        Invocation.setter(
          #lastSeenUsersMap,
          _lastSeenUsersMap,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i18.Friendship> get friendships => (super.noSuchMethod(
        Invocation.getter(#friendships),
        returnValue: <_i18.Friendship>[],
        returnValueForMissingStub: <_i18.Friendship>[],
      ) as List<_i18.Friendship>);

  @override
  set friendships(List<_i18.Friendship>? _friendships) => super.noSuchMethod(
        Invocation.setter(
          #friendships,
          _friendships,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<dynamic> get friendIDs => (super.noSuchMethod(
        Invocation.getter(#friendIDs),
        returnValue: <dynamic>[],
        returnValueForMissingStub: <dynamic>[],
      ) as List<dynamic>);

  @override
  set friendIDs(List<dynamic>? _friendIDs) => super.noSuchMethod(
        Invocation.setter(
          #friendIDs,
          _friendIDs,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get friendshipsLoaded => (super.noSuchMethod(
        Invocation.getter(#friendshipsLoaded),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set friendshipsLoaded(bool? _friendshipsLoaded) => super.noSuchMethod(
        Invocation.setter(
          #friendshipsLoaded,
          _friendshipsLoaded,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get postNotificationOn => (super.noSuchMethod(
        Invocation.getter(#postNotificationOn),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set postNotificationOn(bool? _postNotificationOn) => super.noSuchMethod(
        Invocation.setter(
          #postNotificationOn,
          _postNotificationOn,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get likeNotificationOn => (super.noSuchMethod(
        Invocation.getter(#likeNotificationOn),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set likeNotificationOn(bool? _likeNotificationOn) => super.noSuchMethod(
        Invocation.setter(
          #likeNotificationOn,
          _likeNotificationOn,
        ),
        returnValueForMissingStub: null,
      );

  @override
  double get size => (super.noSuchMethod(
        Invocation.getter(#size),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  set size(double? _size) => super.noSuchMethod(
        Invocation.setter(
          #size,
          _size,
        ),
        returnValueForMissingStub: null,
      );

  @override
  double get x => (super.noSuchMethod(
        Invocation.getter(#x),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  set x(double? _x) => super.noSuchMethod(
        Invocation.setter(
          #x,
          _x,
        ),
        returnValueForMissingStub: null,
      );

  @override
  double get y => (super.noSuchMethod(
        Invocation.getter(#y),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  set y(double? _y) => super.noSuchMethod(
        Invocation.setter(
          #y,
          _y,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool main() => (super.noSuchMethod(
        Invocation.method(
          #main,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool hasFriends() => (super.noSuchMethod(
        Invocation.method(
          #hasFriends,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool didBlockYou() => (super.noSuchMethod(
        Invocation.method(
          #didBlockYou,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool hasNonLoadedFriends() => (super.noSuchMethod(
        Invocation.method(
          #hasNonLoadedFriends,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i19.Future<_i5.DocumentSnapshot<Object?>> getLastFriendshipDocument() =>
      (super.noSuchMethod(
        Invocation.method(
          #getLastFriendshipDocument,
          [],
        ),
        returnValue: _i19.Future<_i5.DocumentSnapshot<Object?>>.value(
            _FakeDocumentSnapshot_4<Object?>(
          this,
          Invocation.method(
            #getLastFriendshipDocument,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i5.DocumentSnapshot<Object?>>.value(
                _FakeDocumentSnapshot_4<Object?>(
          this,
          Invocation.method(
            #getLastFriendshipDocument,
            [],
          ),
        )),
      ) as _i19.Future<_i5.DocumentSnapshot<Object?>>);

  @override
  _i6.Point<double> point() => (super.noSuchMethod(
        Invocation.method(
          #point,
          [],
        ),
        returnValue: _FakePoint_5<double>(
          this,
          Invocation.method(
            #point,
            [],
          ),
        ),
        returnValueForMissingStub: _FakePoint_5<double>(
          this,
          Invocation.method(
            #point,
            [],
          ),
        ),
      ) as _i6.Point<double>);
}

/// A class which mocks [PictureQuery].
///
/// See the documentation for Mockito's code generation for more information.
class MockPictureQuery extends _i1.Mock implements _i20.PictureQuery {
  @override
  _i19.Future<void> removeProfilePicture(String? downloadUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeProfilePicture,
          [downloadUrl],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<String?> uploadAvatar(_i21.File? imageFile) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadAvatar,
          [imageFile],
        ),
        returnValue: _i19.Future<String?>.value(),
        returnValueForMissingStub: _i19.Future<String?>.value(),
      ) as _i19.Future<String?>);
}

/// A class which mocks [UserManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserManager extends _i1.Mock implements _i22.UserManager {
  @override
  _i19.Future<_i4.ImageProvider<Object>> refreshAvatar(_i21.File? file) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshAvatar,
          [file],
        ),
        returnValue: _i19.Future<_i4.ImageProvider<Object>>.value(
            _FakeImageProvider_3<Object>(
          this,
          Invocation.method(
            #refreshAvatar,
            [file],
          ),
        )),
        returnValueForMissingStub: _i19.Future<_i4.ImageProvider<Object>>.value(
            _FakeImageProvider_3<Object>(
          this,
          Invocation.method(
            #refreshAvatar,
            [file],
          ),
        )),
      ) as _i19.Future<_i4.ImageProvider<Object>>);
}

/// A class which mocks [DeviceInfoPlugin].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceInfoPlugin extends _i1.Mock implements _i23.DeviceInfoPlugin {
  @override
  _i19.Future<_i7.AndroidDeviceInfo> get androidInfo => (super.noSuchMethod(
        Invocation.getter(#androidInfo),
        returnValue:
            _i19.Future<_i7.AndroidDeviceInfo>.value(_FakeAndroidDeviceInfo_6(
          this,
          Invocation.getter(#androidInfo),
        )),
        returnValueForMissingStub:
            _i19.Future<_i7.AndroidDeviceInfo>.value(_FakeAndroidDeviceInfo_6(
          this,
          Invocation.getter(#androidInfo),
        )),
      ) as _i19.Future<_i7.AndroidDeviceInfo>);

  @override
  _i19.Future<_i8.IosDeviceInfo> get iosInfo => (super.noSuchMethod(
        Invocation.getter(#iosInfo),
        returnValue: _i19.Future<_i8.IosDeviceInfo>.value(_FakeIosDeviceInfo_7(
          this,
          Invocation.getter(#iosInfo),
        )),
        returnValueForMissingStub:
            _i19.Future<_i8.IosDeviceInfo>.value(_FakeIosDeviceInfo_7(
          this,
          Invocation.getter(#iosInfo),
        )),
      ) as _i19.Future<_i8.IosDeviceInfo>);

  @override
  _i19.Future<_i9.LinuxDeviceInfo> get linuxInfo => (super.noSuchMethod(
        Invocation.getter(#linuxInfo),
        returnValue:
            _i19.Future<_i9.LinuxDeviceInfo>.value(_FakeLinuxDeviceInfo_8(
          this,
          Invocation.getter(#linuxInfo),
        )),
        returnValueForMissingStub:
            _i19.Future<_i9.LinuxDeviceInfo>.value(_FakeLinuxDeviceInfo_8(
          this,
          Invocation.getter(#linuxInfo),
        )),
      ) as _i19.Future<_i9.LinuxDeviceInfo>);

  @override
  _i19.Future<_i10.WebBrowserInfo> get webBrowserInfo => (super.noSuchMethod(
        Invocation.getter(#webBrowserInfo),
        returnValue:
            _i19.Future<_i10.WebBrowserInfo>.value(_FakeWebBrowserInfo_9(
          this,
          Invocation.getter(#webBrowserInfo),
        )),
        returnValueForMissingStub:
            _i19.Future<_i10.WebBrowserInfo>.value(_FakeWebBrowserInfo_9(
          this,
          Invocation.getter(#webBrowserInfo),
        )),
      ) as _i19.Future<_i10.WebBrowserInfo>);

  @override
  _i19.Future<_i11.MacOsDeviceInfo> get macOsInfo => (super.noSuchMethod(
        Invocation.getter(#macOsInfo),
        returnValue:
            _i19.Future<_i11.MacOsDeviceInfo>.value(_FakeMacOsDeviceInfo_10(
          this,
          Invocation.getter(#macOsInfo),
        )),
        returnValueForMissingStub:
            _i19.Future<_i11.MacOsDeviceInfo>.value(_FakeMacOsDeviceInfo_10(
          this,
          Invocation.getter(#macOsInfo),
        )),
      ) as _i19.Future<_i11.MacOsDeviceInfo>);

  @override
  _i19.Future<_i12.WindowsDeviceInfo> get windowsInfo => (super.noSuchMethod(
        Invocation.getter(#windowsInfo),
        returnValue:
            _i19.Future<_i12.WindowsDeviceInfo>.value(_FakeWindowsDeviceInfo_11(
          this,
          Invocation.getter(#windowsInfo),
        )),
        returnValueForMissingStub:
            _i19.Future<_i12.WindowsDeviceInfo>.value(_FakeWindowsDeviceInfo_11(
          this,
          Invocation.getter(#windowsInfo),
        )),
      ) as _i19.Future<_i12.WindowsDeviceInfo>);

  @override
  _i19.Future<_i13.BaseDeviceInfo> get deviceInfo => (super.noSuchMethod(
        Invocation.getter(#deviceInfo),
        returnValue:
            _i19.Future<_i13.BaseDeviceInfo>.value(_FakeBaseDeviceInfo_12(
          this,
          Invocation.getter(#deviceInfo),
        )),
        returnValueForMissingStub:
            _i19.Future<_i13.BaseDeviceInfo>.value(_FakeBaseDeviceInfo_12(
          this,
          Invocation.getter(#deviceInfo),
        )),
      ) as _i19.Future<_i13.BaseDeviceInfo>);
}

/// A class which mocks [ImagePicker].
///
/// See the documentation for Mockito's code generation for more information.
class MockImagePicker extends _i1.Mock implements _i24.ImagePicker {
  @override
  _i19.Future<_i14.XFile?> pickImage({
    required _i14.ImageSource? source,
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    _i14.CameraDevice? preferredCameraDevice = _i14.CameraDevice.rear,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickImage,
          [],
          {
            #source: source,
            #maxWidth: maxWidth,
            #maxHeight: maxHeight,
            #imageQuality: imageQuality,
            #preferredCameraDevice: preferredCameraDevice,
            #requestFullMetadata: requestFullMetadata,
          },
        ),
        returnValue: _i19.Future<_i14.XFile?>.value(),
        returnValueForMissingStub: _i19.Future<_i14.XFile?>.value(),
      ) as _i19.Future<_i14.XFile?>);

  @override
  _i19.Future<List<_i14.XFile>> pickMultiImage({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    int? limit,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickMultiImage,
          [],
          {
            #maxWidth: maxWidth,
            #maxHeight: maxHeight,
            #imageQuality: imageQuality,
            #limit: limit,
            #requestFullMetadata: requestFullMetadata,
          },
        ),
        returnValue: _i19.Future<List<_i14.XFile>>.value(<_i14.XFile>[]),
        returnValueForMissingStub:
            _i19.Future<List<_i14.XFile>>.value(<_i14.XFile>[]),
      ) as _i19.Future<List<_i14.XFile>>);

  @override
  _i19.Future<_i14.XFile?> pickMedia({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickMedia,
          [],
          {
            #maxWidth: maxWidth,
            #maxHeight: maxHeight,
            #imageQuality: imageQuality,
            #requestFullMetadata: requestFullMetadata,
          },
        ),
        returnValue: _i19.Future<_i14.XFile?>.value(),
        returnValueForMissingStub: _i19.Future<_i14.XFile?>.value(),
      ) as _i19.Future<_i14.XFile?>);

  @override
  _i19.Future<List<_i14.XFile>> pickMultipleMedia({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    int? limit,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickMultipleMedia,
          [],
          {
            #maxWidth: maxWidth,
            #maxHeight: maxHeight,
            #imageQuality: imageQuality,
            #limit: limit,
            #requestFullMetadata: requestFullMetadata,
          },
        ),
        returnValue: _i19.Future<List<_i14.XFile>>.value(<_i14.XFile>[]),
        returnValueForMissingStub:
            _i19.Future<List<_i14.XFile>>.value(<_i14.XFile>[]),
      ) as _i19.Future<List<_i14.XFile>>);

  @override
  _i19.Future<_i14.XFile?> pickVideo({
    required _i14.ImageSource? source,
    _i14.CameraDevice? preferredCameraDevice = _i14.CameraDevice.rear,
    Duration? maxDuration,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickVideo,
          [],
          {
            #source: source,
            #preferredCameraDevice: preferredCameraDevice,
            #maxDuration: maxDuration,
          },
        ),
        returnValue: _i19.Future<_i14.XFile?>.value(),
        returnValueForMissingStub: _i19.Future<_i14.XFile?>.value(),
      ) as _i19.Future<_i14.XFile?>);

  @override
  _i19.Future<_i14.LostDataResponse> retrieveLostData() => (super.noSuchMethod(
        Invocation.method(
          #retrieveLostData,
          [],
        ),
        returnValue:
            _i19.Future<_i14.LostDataResponse>.value(_FakeLostDataResponse_13(
          this,
          Invocation.method(
            #retrieveLostData,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i14.LostDataResponse>.value(_FakeLostDataResponse_13(
          this,
          Invocation.method(
            #retrieveLostData,
            [],
          ),
        )),
      ) as _i19.Future<_i14.LostDataResponse>);

  @override
  bool supportsImageSource(_i14.ImageSource? source) => (super.noSuchMethod(
        Invocation.method(
          #supportsImageSource,
          [source],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
}

/// A class which mocks [ImageCropper].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageCropper extends _i1.Mock implements _i25.ImageCropper {
  @override
  _i19.Future<_i26.CroppedFile?> cropImage({
    required String? sourcePath,
    int? maxWidth,
    int? maxHeight,
    _i26.CropAspectRatio? aspectRatio,
    List<_i26.CropAspectRatioPreset>? aspectRatioPresets = const [
      _i26.CropAspectRatioPreset.original,
      _i26.CropAspectRatioPreset.square,
      _i26.CropAspectRatioPreset.ratio3x2,
      _i26.CropAspectRatioPreset.ratio4x3,
      _i26.CropAspectRatioPreset.ratio16x9,
    ],
    _i26.CropStyle? cropStyle = _i26.CropStyle.rectangle,
    _i26.ImageCompressFormat? compressFormat = _i26.ImageCompressFormat.jpg,
    int? compressQuality = 90,
    List<_i26.PlatformUiSettings>? uiSettings,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cropImage,
          [],
          {
            #sourcePath: sourcePath,
            #maxWidth: maxWidth,
            #maxHeight: maxHeight,
            #aspectRatio: aspectRatio,
            #aspectRatioPresets: aspectRatioPresets,
            #cropStyle: cropStyle,
            #compressFormat: compressFormat,
            #compressQuality: compressQuality,
            #uiSettings: uiSettings,
          },
        ),
        returnValue: _i19.Future<_i26.CroppedFile?>.value(),
        returnValueForMissingStub: _i19.Future<_i26.CroppedFile?>.value(),
      ) as _i19.Future<_i26.CroppedFile?>);

  @override
  _i19.Future<_i26.CroppedFile?> recoverImage() => (super.noSuchMethod(
        Invocation.method(
          #recoverImage,
          [],
        ),
        returnValue: _i19.Future<_i26.CroppedFile?>.value(),
        returnValueForMissingStub: _i19.Future<_i26.CroppedFile?>.value(),
      ) as _i19.Future<_i26.CroppedFile?>);
}

/// A class which mocks [Permission].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockPermission extends _i1.Mock implements _i27.Permission {
  @override
  int get value => (super.noSuchMethod(
        Invocation.getter(#value),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);
}

/// A class which mocks [ErrorHandling].
///
/// See the documentation for Mockito's code generation for more information.
class MockErrorHandling extends _i1.Mock implements _i28.ErrorHandling {}
