// Mocks generated by Mockito 5.4.4 from annotations
// in befriend/test/models/authentication/consent_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:befriend/views/dialogs/home/consent_dialog.dart' as _i8;
import 'package:flutter/foundation.dart' as _i3;
import 'package:flutter/material.dart' as _i2;
import 'package:flutter/src/widgets/notification_listener.dart' as _i5;
import 'package:google_mobile_ads/google_mobile_ads.dart' as _i4;
import 'package:google_mobile_ads/src/ad_inspector_containers.dart' as _i11;
import 'package:google_mobile_ads/src/ump/consent_request_parameters.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:webview_flutter/webview_flutter.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWidget_0 extends _i1.SmartFake implements _i2.Widget {
  _FakeWidget_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeInheritedWidget_1 extends _i1.SmartFake
    implements _i2.InheritedWidget {
  _FakeInheritedWidget_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeDiagnosticsNode_2 extends _i1.SmartFake
    implements _i3.DiagnosticsNode {
  _FakeDiagnosticsNode_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({
    _i3.TextTreeConfiguration? parentConfiguration,
    _i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info,
  }) =>
      super.toString();
}

class _FakeInitializationStatus_3 extends _i1.SmartFake
    implements _i4.InitializationStatus {
  _FakeInitializationStatus_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRequestConfiguration_4 extends _i1.SmartFake
    implements _i4.RequestConfiguration {
  _FakeRequestConfiguration_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BuildContext].
///
/// See the documentation for Mockito's code generation for more information.
class MockBuildContext extends _i1.Mock implements _i2.BuildContext {
  @override
  _i2.Widget get widget => (super.noSuchMethod(
        Invocation.getter(#widget),
        returnValue: _FakeWidget_0(
          this,
          Invocation.getter(#widget),
        ),
        returnValueForMissingStub: _FakeWidget_0(
          this,
          Invocation.getter(#widget),
        ),
      ) as _i2.Widget);

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get debugDoingBuild => (super.noSuchMethod(
        Invocation.getter(#debugDoingBuild),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i2.InheritedWidget dependOnInheritedElement(
    _i2.InheritedElement? ancestor, {
    Object? aspect,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #dependOnInheritedElement,
          [ancestor],
          {#aspect: aspect},
        ),
        returnValue: _FakeInheritedWidget_1(
          this,
          Invocation.method(
            #dependOnInheritedElement,
            [ancestor],
            {#aspect: aspect},
          ),
        ),
        returnValueForMissingStub: _FakeInheritedWidget_1(
          this,
          Invocation.method(
            #dependOnInheritedElement,
            [ancestor],
            {#aspect: aspect},
          ),
        ),
      ) as _i2.InheritedWidget);

  @override
  void visitAncestorElements(_i2.ConditionalElementVisitor? visitor) =>
      super.noSuchMethod(
        Invocation.method(
          #visitAncestorElements,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void visitChildElements(_i2.ElementVisitor? visitor) => super.noSuchMethod(
        Invocation.method(
          #visitChildElements,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispatchNotification(_i5.Notification? notification) =>
      super.noSuchMethod(
        Invocation.method(
          #dispatchNotification,
          [notification],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.DiagnosticsNode describeElement(
    String? name, {
    _i3.DiagnosticsTreeStyle? style = _i3.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeElement,
          [name],
          {#style: style},
        ),
        returnValue: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #describeElement,
            [name],
            {#style: style},
          ),
        ),
        returnValueForMissingStub: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #describeElement,
            [name],
            {#style: style},
          ),
        ),
      ) as _i3.DiagnosticsNode);

  @override
  _i3.DiagnosticsNode describeWidget(
    String? name, {
    _i3.DiagnosticsTreeStyle? style = _i3.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeWidget,
          [name],
          {#style: style},
        ),
        returnValue: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #describeWidget,
            [name],
            {#style: style},
          ),
        ),
        returnValueForMissingStub: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #describeWidget,
            [name],
            {#style: style},
          ),
        ),
      ) as _i3.DiagnosticsNode);

  @override
  List<_i3.DiagnosticsNode> describeMissingAncestor(
          {required Type? expectedAncestorType}) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeMissingAncestor,
          [],
          {#expectedAncestorType: expectedAncestorType},
        ),
        returnValue: <_i3.DiagnosticsNode>[],
        returnValueForMissingStub: <_i3.DiagnosticsNode>[],
      ) as List<_i3.DiagnosticsNode>);

  @override
  _i3.DiagnosticsNode describeOwnershipChain(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeOwnershipChain,
          [name],
        ),
        returnValue: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #describeOwnershipChain,
            [name],
          ),
        ),
        returnValueForMissingStub: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #describeOwnershipChain,
            [name],
          ),
        ),
      ) as _i3.DiagnosticsNode);
}

/// A class which mocks [ConsentInformation].
///
/// See the documentation for Mockito's code generation for more information.
class MockConsentInformation extends _i1.Mock
    implements _i4.ConsentInformation {
  @override
  void requestConsentInfoUpdate(
    _i6.ConsentRequestParameters? params,
    _i4.OnConsentInfoUpdateSuccessListener? successListener,
    _i4.OnConsentInfoUpdateFailureListener? failureListener,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #requestConsentInfoUpdate,
          [
            params,
            successListener,
            failureListener,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<bool> isConsentFormAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isConsentFormAvailable,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<_i4.ConsentStatus> getConsentStatus() => (super.noSuchMethod(
        Invocation.method(
          #getConsentStatus,
          [],
        ),
        returnValue:
            _i7.Future<_i4.ConsentStatus>.value(_i4.ConsentStatus.notRequired),
        returnValueForMissingStub:
            _i7.Future<_i4.ConsentStatus>.value(_i4.ConsentStatus.notRequired),
      ) as _i7.Future<_i4.ConsentStatus>);

  @override
  _i7.Future<void> reset() => (super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [ConsentDialog].
///
/// See the documentation for Mockito's code generation for more information.
class MockConsentDialog extends _i1.Mock implements _i8.ConsentDialog {
  @override
  void showConsentDialog(
    _i2.BuildContext? context, {
    required String? dialogName,
    required String? fileAddress,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #showConsentDialog,
          [context],
          {
            #dialogName: dialogName,
            #fileAddress: fileAddress,
          },
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MobileAds].
///
/// See the documentation for Mockito's code generation for more information.
class MockMobileAds extends _i1.Mock implements _i4.MobileAds {
  @override
  _i7.Future<_i4.InitializationStatus> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i7.Future<_i4.InitializationStatus>.value(
            _FakeInitializationStatus_3(
          this,
          Invocation.method(
            #initialize,
            [],
          ),
        )),
        returnValueForMissingStub: _i7.Future<_i4.InitializationStatus>.value(
            _FakeInitializationStatus_3(
          this,
          Invocation.method(
            #initialize,
            [],
          ),
        )),
      ) as _i7.Future<_i4.InitializationStatus>);

  @override
  _i7.Future<_i4.RequestConfiguration> getRequestConfiguration() =>
      (super.noSuchMethod(
        Invocation.method(
          #getRequestConfiguration,
          [],
        ),
        returnValue: _i7.Future<_i4.RequestConfiguration>.value(
            _FakeRequestConfiguration_4(
          this,
          Invocation.method(
            #getRequestConfiguration,
            [],
          ),
        )),
        returnValueForMissingStub: _i7.Future<_i4.RequestConfiguration>.value(
            _FakeRequestConfiguration_4(
          this,
          Invocation.method(
            #getRequestConfiguration,
            [],
          ),
        )),
      ) as _i7.Future<_i4.RequestConfiguration>);

  @override
  _i7.Future<void> updateRequestConfiguration(
          _i4.RequestConfiguration? requestConfiguration) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRequestConfiguration,
          [requestConfiguration],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setSameAppKeyEnabled(bool? isEnabled) => (super.noSuchMethod(
        Invocation.method(
          #setSameAppKeyEnabled,
          [isEnabled],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setAppMuted(bool? muted) => (super.noSuchMethod(
        Invocation.method(
          #setAppMuted,
          [muted],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setAppVolume(double? volume) => (super.noSuchMethod(
        Invocation.method(
          #setAppVolume,
          [volume],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> disableSDKCrashReporting() => (super.noSuchMethod(
        Invocation.method(
          #disableSDKCrashReporting,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> disableMediationInitialization() => (super.noSuchMethod(
        Invocation.method(
          #disableMediationInitialization,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String> getVersionString() => (super.noSuchMethod(
        Invocation.method(
          #getVersionString,
          [],
        ),
        returnValue: _i7.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #getVersionString,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #getVersionString,
            [],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<void> openDebugMenu(String? adUnitId) => (super.noSuchMethod(
        Invocation.method(
          #openDebugMenu,
          [adUnitId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> registerWebView(_i10.WebViewController? webViewController) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerWebView,
          [webViewController],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void openAdInspector(_i11.OnAdInspectorClosedListener? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #openAdInspector,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
}
